<?php
/**
 * EntityExtractionResponseAnnotationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DandelionPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dandelion Swagger API
 *
 * Unofficial Dandelion Swagger API definition
 *
 * OpenAPI spec version: 0.0.1
 * Contact: g.prinaricotti@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DandelionPHP;

/**
 * EntityExtractionResponseAnnotationTest Class Doc Comment
 *
 * @category    Class */
// * @description EntityExtractionResponseAnnotation
/**
 * @package     DandelionPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EntityExtractionResponseAnnotationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EntityExtractionResponseAnnotation"
     */
    public function testEntityExtractionResponseAnnotation()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {

    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {

    }

    /**
     * Test attribute "confidence"
     */
    public function testPropertyConfidence()
    {

    }

    /**
     * Test attribute "spot"
     */
    public function testPropertySpot()
    {

    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {

    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {

    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {

    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {

    }

    /**
     * Test attribute "abstract"
     */
    public function testPropertyAbstract()
    {

    }

    /**
     * Test attribute "lod"
     */
    public function testPropertyLod()
    {

    }

    /**
     * Test attribute "alternate_labels"
     */
    public function testPropertyAlternateLabels()
    {

    }

}
