<?php
/**
 * EntityExtractionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DandelionPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dandelion Swagger API
 *
 * Unofficial Dandelion Swagger API definition
 *
 * OpenAPI spec version: 0.0.1
 * Contact: g.prinaricotti@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DandelionPHP;

/**
 * EntityExtractionResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description EntityExtractionResponse
/**
 * @package     DandelionPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EntityExtractionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EntityExtractionResponse"
     */
    public function testEntityExtractionResponse()
    {

    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {

    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {

    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {

    }

    /**
     * Test attribute "lang_confidence"
     */
    public function testPropertyLangConfidence()
    {

    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "annotations"
     */
    public function testPropertyAnnotations()
    {

    }

}
